custom:
  - "https://paxzeronode.github.io/"
  - "https://github.com/PaxZeroNode/PaxZeroNode.github.io/issues/new/choose"
  - "https://github.com/PaxZeroNode/PaxZeroNode.github.io/releases/tag/starter-kit-v1"
